backend: 
  name: github
  branch: master
  repo: adampugh/gatsby-pro-2


media_folder: static/img
public_folder: /img

collections:
  - name: "team"
    label: "Team"
    folder: "src/team"
    create: true
    slug: "{{slug}}"
    fields: 
      - { label: "Team Member", name: "title", widget: "string"}
      - { label: "Bio", name: "bio", widget: "string"}